#!/bin/sh
#
#	Crontab script by Monellik
#

if test -f  psybnc.conf
then
  rm -rf psybncchk
  echo --- creating psybncchk
  echo \#!/bin/sh >psybncchk
  echo \# This is the crontab script for psybnc. >>psybncchk
  echo \# >>psybncchk
  echo \# Please change the following path to your psybnc-directory. >>psybncchk
  echo \ >>psybncchk
  echo \PSYBNCPATH=$PWD >>psybncchk
  echo \ >>psybncchk
  echo \# the rest should be kept as is >>psybncchk
  echo \ >>psybncchk
  echo \if test -r \$PSYBNCPATH/psybnc.pid\; \then >>psybncchk
  echo \    PSYPID=\$\(cat \$PSYBNCPATH/psybnc.pid\) >>psybncchk
  echo \    \if \$\(kill -CHLD \$PSYPID \>/dev/null 2\>\&1\) >>psybncchk
  echo \    \then >>psybncchk
  echo \        \exit 0 >>psybncchk
  echo \    \fi >>psybncchk
  echo \fi >>psybncchk
  echo \cd \$PSYBNCPATH >>psybncchk
  echo \./psybnc \&\>/dev/null >>psybncchk
  chmod 700 psybncchk
  echo --- Updating crontab
  echo 0,10,20,30,40,50 \* \* \* \* $PWD/psybncchk \>/dev/null 2>&1 >crontab.tmp
  crontab crontab.tmp
  rm crontab.tmp
  crontab -l
else
  echo cannot find psybnc
fi


